# -*- conf -*-

# Shell Configuration
shell=/bin/zsh
term=foot
login-shell=no

# Window Configuration
app-id=foot
title=Terminal
pad=15x15

# Font Configuration
font=JetBrainsMono Nerd Font:size=10, Symbols Nerd Font:size=10
dpi-aware=yes

[environment]
# name=Terminal

[bell]
urgent=no
notify=no
command-focused=no

[scrollback]
lines=10000
multiplier=6.0
indicator-position=relative
indicator-format=""

[url]
launch=xdg-open ${url}

[cursor]
style=block
blink=no
beam-thickness=1.5

[mouse]
hide-when-typing=yes
alternate-scroll-mode=yes

# [colors-dark]
# alpha=1.0
# background=f7f6f2
# foreground=1a1a18

# # Black
# regular0=282828
# bright0=5c5c5c

# # Red
# regular1=c0392b
# bright1=e53935

# # Green
# regular2=2e7d32
# bright2=388e3c

# # Yellow
# regular3=9e6b00
# bright3=c47f00

# # Blue
# regular4=1565c0
# bright4=1976d2

# # Magenta
# regular5=6a1b9a
# bright5=8e24aa

# # Cyan
# regular6=00695c
# bright6=00897b

# # White
# regular7=546e7a
# bright7=90a4ae

# # Selection
# selection-foreground=ffffff
# selection-background=1565c0
# urls=1565c0

[colors-dark]
# Kanagawa-style theme
alpha=0.85
background=020202
foreground=dcdcdc

# Black
regular0=181818
bright0=2d2d2d

# Red
regular1=c34043
bright1=e82424

# Green
regular2=76946a
bright2=98bb6c

# Yellow
regular3=c0a36e
bright3=e6c384

# Blue
regular4=658594
bright4=7fb4ca

# Magenta
regular5=957fb8
bright5=938aa9

# Cyan
regular6=6a9589
bright6=7aa89f

# White
regular7=c8c093
bright7=dcdcdc

## Selection
selection-foreground=000000
selection-background=c0a36e
urls=7fb4ca

[csd]
border-width=0
size=0

[key-bindings]
unicode-input=none
scrollback-up-page=Shift+Up
scrollback-down-page=Shift+Down
clipboard-copy=Control+Shift+c XF86Copy
clipboard-paste=Control+Shift+v XF86Paste
primary-paste=Shift+Insert
search-start=Control+Shift+r
font-increase=Control+plus Control+equal Control+KP_Add
font-decrease=Control+minus Control+KP_Subtract
font-reset=Control+0 Control+KP_0
spawn-terminal=Control+Shift+n
show-urls-launch=Control+Shift+u

[search-bindings]
cancel=Control+g Control+c Escape
commit=Return
find-prev=Control+r
find-next=Control+s
cursor-left=Left Control+b
cursor-right=Right Control+f
delete-prev=BackSpace
delete-next=Delete
extend-to-word-boundary=Control+w
clipboard-paste=Control+v Control+Shift+v Control+y XF86Paste

[url-bindings]
cancel=Control+g Control+c Control+d Escape
toggle-url-visible=t

[mouse-bindings]
selection-override-modifiers=Shift
primary-paste=BTN_MIDDLE
select-begin=BTN_LEFT
select-begin-block=Control+BTN_LEFT
select-extend=BTN_RIGHT
select-extend-character-wise=Control+BTN_RIGHT
select-word=BTN_LEFT-2
select-word-whitespace=Control+BTN_LEFT-2
